import { create } from 'zustand';

export const useTickerStore = create((set, get) => ({
  activeTab: 'charts',
  compareTicker: '',
  period: null,
  visibleRange: null,
  correlagDays: 1,
  showChat: false,
  showWatchlist: true,
  showTrump: false,
  showNvd: false,
  showOtx: false,
  showKev: false,
  showNews: false,
  hidePrice: false,
  hideVolatility: false,
  hideNewsSentiment: false,
  hideIntelligence: false,
  showCyberNews: false,
  hideCyberNewsSentiment: false,

  setActiveTab: (v) => set({ activeTab: v }),
  setCompareTicker: (v) => set({ compareTicker: v }),
  setPeriod: (v) => set({ period: v }),
  setVisibleRange: (v) => set({ visibleRange: v }),
  setCorrelagDays: (v) => set({ correlagDays: v }),
  setShowChat: (v) => set({ showChat: typeof v === 'function' ? v(get().showChat) : v }),
  setShowWatchlist: (v) => set({ showWatchlist: typeof v === 'function' ? v(get().showWatchlist) : v }),
  setShowTrump: (v) => set({ showTrump: v }),
  setShowNvd: (v) => set({ showNvd: v }),
  setShowOtx: (v) => set({ showOtx: v }),
  setShowKev: (v) => set({ showKev: v }),
  setShowNews: (v) => set({ showNews: v }),
  setHidePrice: (v) => set({ hidePrice: v }),
  setHideVolatility: (v) => set({ hideVolatility: v }),
  setHideNewsSentiment: (v) => set({ hideNewsSentiment: v }),
  setHideIntelligence: (v) => set({ hideIntelligence: v }),
  setShowCyberNews: (v) => set({ showCyberNews: v }),
  setHideCyberNewsSentiment: (v) => set({ hideCyberNewsSentiment: v }),

  reset: () =>
    set({
      activeTab: 'charts',
      compareTicker: '',
      period: null,
      visibleRange: null,
      correlagDays: 1,
      showChat: false,
      showTrump: false,
      showNvd: false,
      showOtx: false,
      showKev: false,
      showNews: false,
      hidePrice: false,
      hideVolatility: false,
      hideNewsSentiment: false,
      hideIntelligence: false,
      showCyberNews: false,
      hideCyberNewsSentiment: false,
    }),
}));
