/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate via Clerk
         * @description Verifies a Clerk session token. Creates the user on first login and returns a JWT + user object.
         */
        post: operations["AuthController_clerkAuth_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the authenticated user derived from the Bearer JWT.
         */
        get: operations["AuthController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/anthropic/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Anthropic status
         * @description Checks whether the Anthropic API key is configured and returns the active model name.
         */
        get: operations["NewsController_anthropicStatus_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/analysis/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sentiment scores
         * @description Returns stored sentiment, importance, and relevance scores for all analysed news articles for the ticker.
         */
        get: operations["NewsController_getAnalysis_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/analyze/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue news for analysis
         * @description Queues all unanalysed news articles for the ticker to RabbitMQ for Anthropic sentiment processing. Rate limited to 10 req/60s.
         */
        post: operations["NewsController_analyze_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/analyze/{ticker}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analysis progress stream (SSE)
         * @description Server-Sent Events stream reporting progress of a running news analysis job. Accepts ?token= instead of Authorization header.
         */
        get: operations["NewsController_progress_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/correlation/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * News–price correlation
         * @description Correlates news sentiment events with stock price movements using Pearson correlation and lag-bucketed impact analysis.
         */
        get: operations["NewsController_correlation_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trump/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All Truth Social posts
         * @description Returns all stored Trump Truth Social posts with their AI-generated ticker mention analysis.
         */
        get: operations["TrumpController_getAllPosts_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trump/posts/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Posts mentioning a ticker
         * @description Returns only the Trump posts whose AI analysis identified a mention of the given ticker.
         */
        get: operations["TrumpController_getPostsForTicker_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trump/correlate/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trump post–price correlation
         * @description Correlates dates of Trump posts mentioning the ticker with subsequent stock price movements.
         */
        get: operations["TrumpController_getCorrelation_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trump/lag-impact/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trump post lag impact
         * @description Returns lag-bucketed average stock price changes in the days following positive, negative, and neutral Trump post sentiment.
         */
        get: operations["TrumpController_getLagImpact_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reddit/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subreddit posts */
        get: operations["RedditController_getPosts_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reddit/comments/{subreddit}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get post comments */
        get: operations["RedditController_getComments_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threat-intel/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source sync status
         * @description Returns record counts and last-sync timestamps for all threat intel sources: CISA KEV, NVD, AlienVault OTX, and MISP.
         */
        get: operations["ThreatIntelController_status_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threat-intel/list/{source}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List threat intel entries
         * @description Paginated entries for a single source. kev and nvd support full-text search and severity/ransomware filtering. otx and misp return { configured: false } when the API key is missing.
         */
        get: operations["ThreatIntelController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threat-intel/correlate/{source}/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Threat intel–price correlation
         * @description Correlates threat event dates for a source with a ticker's stock price movements. Requires at least 4 threat events to compute.
         */
        get: operations["ThreatIntelController_correlate_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/articles/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process backend article
         * @description Runs backend content analysis pipeline on a submitted article.
         */
        post: operations["IntelligenceController_processBackendArticle_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get entities
         * @description Returns all entities that match tracked companies.
         */
        get: operations["IntelligenceController_getBackendEntities_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/entities/{entityId}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get entity articles
         * @description Returns all articles associated with an entity.
         */
        get: operations["IntelligenceController_getBackendEntityArticles_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/entities/{entityId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get entity summary
         * @description Returns the aggregated intelligence summary for an entity.
         */
        get: operations["IntelligenceController_getBackendEntitySummary_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global signals
         * @description Returns aggregated intelligence signals across all entities.
         */
        get: operations["IntelligenceController_getBackendGlobalSignals_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/sentiment-correlations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sentiment correlations
         * @description Correlates entity sentiment scores with stock price movements for all tracked companies.
         */
        get: operations["IntelligenceController_getAllSentimentCorrelations_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyber-news/tickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All tickers with cyber news */
        get: operations["CyberNewsController_getTickers_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyber-news/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent articles across all companies */
        get: operations["CyberNewsController_getRecent_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyber-news/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated topics from all analyses */
        get: operations["CyberNewsController_getTopics_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyber-news/{ticker}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sentiment summary for a ticker */
        get: operations["CyberNewsController_getSummary_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyber-news/{ticker}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Articles for a ticker */
        get: operations["CyberNewsController_getArticles_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyber-news/correlations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sentiment ↔ price correlation across all tickers */
        get: operations["CyberNewsController_getCorrelations_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit log
         * @description Paginated audit log of all user actions, newest first. Filterable by userId and action type. Admin only.
         */
        get: operations["AdminController_getAudit_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/trigger/{job}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger cron job
         * @description Manually triggers a background job outside its normal schedule. Admin only.
         */
        post: operations["AdminController_triggerJob_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Domain events stream (SSE)
         * @description Persistent Server-Sent Events stream delivering real-time domain events: news.analyzed, stocks.updated, trump.updated, and threatintel.updated. Accepts ?token= instead of Authorization header.
         */
        get: operations["NotificationsController_stream_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetricsController_getMetrics_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/research/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Market research stream (SSE)
         * @description Streams AI-generated market research for a ticker across three sections: Latest News, Analyst Outlook, and Competitive Landscape. Accepts ?token= instead of Authorization header. Rate limited to 5 req/60s.
         */
        get: operations["ResearchController_streamResearch_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI chat stream (SSE)
         * @description Streams a conversational AI response as Server-Sent Events. Pass the full message history to maintain context across turns. Rate limited to 10 req/60s.
         */
        post: operations["ResearchController_streamChat_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alpaca/bars/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Intraday 1-minute bars
         * @description Returns all 1-minute OHLCV bars for a ticker on a given trading day via Alpaca.
         */
        get: operations["AlpacaController_getBars_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all companies
         * @description Returns the full ticker → company name map for all tracked companies.
         */
        get: operations["StockController_getCompanies_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/correlation-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pearson correlation matrix
         * @description Full NxN Pearson correlation matrix for all companies using log-returns. Cached server-side with a 7-day TTL.
         */
        get: operations["StockController_correlationMatrix_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/correlate/{tickerA}/{tickerB}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Correlate two stocks
         * @description Computes Pearson correlation between two tickers using log-returns over a configurable window.
         */
        get: operations["StockController_correlate_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/sparklines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sparkline data
         * @description Lightweight last-30-day price series for multiple tickers in one request. Cached server-side with a 24h TTL.
         */
        get: operations["StockController_getSparklines_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/simulation-presets/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Simulation presets
         * @description Returns pre-built buy/sell signal strategies for a ticker, ready to pass to POST /simulate/:ticker.
         */
        get: operations["StockController_getPresets_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full ticker data
         * @description Returns price history, latest news articles, Yahoo Finance summary, and trend/momentum/volatility analysis for one ticker.
         */
        get: operations["StockController_getTicker_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/simulate/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run backtest simulation
         * @description Runs a portfolio backtest for a ticker given a sequence of buy/sell actions with dates and share values.
         */
        post: operations["StockController_simulate_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and readiness health check */
        get: operations["HealthController_check_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ClerkAuthDto: {
            /** @description Clerk session token */
            token: string;
        };
        UserDto: {
            /** @description User UUID */
            id: string;
            username: string;
            /** @enum {string} */
            role: "user" | "admin";
            email?: string;
        };
        AuthResponseDto: {
            /** @description Signed JWT for subsequent requests */
            token: string;
            user: components["schemas"]["UserDto"];
        };
        ArticleSentimentDto: {
            /** @description Sentiment score -1 (negative) to 1 (positive) */
            sentiment: number;
            /** @description Editorial importance 1–10 */
            importance: number;
            /** @description Ticker relevance 1–10 */
            relevance: number;
            summary?: string;
            topics?: string[];
            catalyst?: boolean;
            timeframe?: string;
        };
        RollingCorrelationDto: {
            index: number;
            /** @description YYYY-MM-DD */
            date?: string | null;
            r: number;
            pValue: number;
        };
        CorrelationResultDto: {
            /** @description Pearson r coefficient (-1 to 1) */
            r: number;
            pValue: number;
            /** @description True when p < 0.05 */
            significant: boolean;
            /** @description 95% confidence interval [lower, upper] */
            ci: number[];
            /** @description Number of data points used */
            n: number;
            lagDays: number;
            /** @description Source of events */
            source: string;
            interpretation: string;
            rolling?: components["schemas"]["RollingCorrelationDto"][];
        };
        LagBucketDto: {
            /** @description Number of events in bucket */
            n: number;
            avgChangePct?: number | null;
        };
        LagImpactResultDto: {
            windowDays: number;
            positive: components["schemas"]["LagBucketDto"];
            negative: components["schemas"]["LagBucketDto"];
            neutral: components["schemas"]["LagBucketDto"];
        };
        CorrelationWithImpactDto: {
            correlation: components["schemas"]["CorrelationResultDto"];
            lagImpact: components["schemas"]["LagImpactResultDto"];
        };
        TrumpPostDto: {
            id: string;
            /** @description ISO timestamp */
            created_at: string;
            content: string;
            url?: string;
            /** @enum {string} */
            sentiment?: "positive" | "negative" | "neutral";
            tags?: string[];
            /** @description ISO timestamp of AI analysis */
            analyzed_at?: string;
        };
        KevStatusDto: {
            /** @description Total record count */
            count: number;
            syncedAt?: string | null;
            recentCount: number;
            ransomwareCount: number;
        };
        NvdStatusDto: {
            fetched: number;
            syncedAt?: string | null;
            criticalCount: number;
            highCount: number;
        };
        OtxStatusDto: {
            configured: boolean;
            count?: number | null;
            syncedAt?: string | null;
        };
        ThreatIntelStatusResponseDto: {
            kev: components["schemas"]["KevStatusDto"];
            nvd: components["schemas"]["NvdStatusDto"];
            otx: components["schemas"]["OtxStatusDto"];
            misp: components["schemas"]["OtxStatusDto"];
        };
        AuditEntryDto: {
            id: string;
            userId: string;
            username: string;
            action: string;
            meta: {
                [key: string]: unknown;
            };
            /** @description ISO timestamp */
            timestamp: string;
        };
        PaginatedAuditDto: {
            total: number;
            entries: components["schemas"]["AuditEntryDto"][];
        };
        ChatMessageDto: {
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
        };
        ChatBodyDto: {
            messages: components["schemas"]["ChatMessageDto"][];
            context?: string;
        };
        SparklineDto: {
            closes: number[];
            dates: string[];
            latestPrice?: number | null;
            changePct?: number | null;
        };
        QuoteDto: {
            /** @description YYYY-MM-DD */
            date: string;
            open: number;
            high: number;
            low: number;
            close: number;
            adjclose?: number;
            volume?: number;
        };
        SimulationActionDto: {
            /**
             * @description Trade date (YYYY-MM-DD)
             * @example 2024-01-15
             */
            date: string;
            /** @enum {string} */
            type: "buy" | "sell";
            value: number;
        };
        SimulateBodyDto: {
            /** @default [] */
            actions: components["schemas"]["SimulationActionDto"][];
        };
        SimulationTransactionDto: {
            /** @description YYYY-MM-DD */
            date: string;
            /** @enum {string} */
            type: "buy" | "sell";
            shares: number;
            price: number;
            value: number;
            sharesAfter: number;
            portfolioValue: number;
        };
        PortfolioDataPointDto: {
            /** @description YYYY-MM-DD */
            date: string;
            value: number;
        };
        SimulationResultDto: {
            finalCash: number;
            finalShares: number;
            sharesValue: number;
            cashWithdrawn: number;
            finalPortfolioValue: number;
            totalInvested: number;
            profit: number;
            /** @example 12.34% */
            profitPercent: string;
            transactions: components["schemas"]["SimulationTransactionDto"][];
            portfolioHistory: components["schemas"]["PortfolioDataPointDto"][];
            priceHistory: components["schemas"]["PortfolioDataPointDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_clerkAuth_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClerkAuthDto"];
            };
        };
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Invalid Clerk token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NewsController_anthropicStatus_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description { url: string, model: string } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NewsController_getAnalysis_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticker symbol */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["ArticleSentimentDto"];
                    };
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NewsController_analyze_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticker symbol */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description { queued: number, total: number } */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NewsController_progress_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticker symbol */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream: { type, ticker, done?, progress? } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NewsController_correlation_v1: {
        parameters: {
            query?: {
                /** @description Number of days to shift events forward */
                lagDays?: number;
            };
            header?: never;
            path: {
                /** @description Ticker symbol */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationWithImpactDto"];
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrumpController_getAllPosts_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrumpPostDto"][];
                };
            };
        };
    };
    TrumpController_getPostsForTicker_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticker symbol */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrumpPostDto"][];
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrumpController_getCorrelation_v1: {
        parameters: {
            query?: {
                /** @description Number of days to shift events forward */
                lagDays?: number;
            };
            header?: never;
            path: {
                /** @description Ticker symbol */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationWithImpactDto"];
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrumpController_getLagImpact_v1: {
        parameters: {
            query?: {
                /** @description Number of days to shift events forward */
                lagDays?: number;
            };
            header?: never;
            path: {
                /** @description Ticker symbol */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LagImpactResultDto"];
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RedditController_getPosts_v1: {
        parameters: {
            query?: {
                /** @description One of: ExperiencedDevs, cybersecurity */
                subreddit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of Reddit posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown subreddit */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RedditController_getComments_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subreddit name */
                subreddit: string;
                /** @description Post ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of Reddit comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ThreatIntelController_status_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreatIntelStatusResponseDto"];
                };
            };
        };
    };
    ThreatIntelController_list_v1: {
        parameters: {
            query?: {
                /** @description Filter by company name (kev, nvd, otx) */
                company?: unknown;
                /** @description Filter ransomware-associated entries (kev only) */
                ransomware?: unknown;
                /** @description Severity filter: LOW | MEDIUM | HIGH | CRITICAL (nvd only) */
                severity?: unknown;
                /** @description Full-text search (kev, nvd) */
                search?: unknown;
            };
            header?: never;
            path: {
                /** @description Source name */
                source: "kev" | "nvd" | "otx" | "misp";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description { total, items, syncedAt, configured? } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid pagination params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ThreatIntelController_correlate_v1: {
        parameters: {
            query?: {
                /** @description Number of days to shift events forward */
                lagDays?: number;
            };
            header?: never;
            path: {
                /** @description Source name */
                source: "kev" | "nvd" | "otx";
                /** @description Ticker symbol */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationWithImpactDto"];
                };
            };
            /** @description Not enough threat events (< 4) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown source or ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IntelligenceController_processBackendArticle_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processed article result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IntelligenceController_getBackendEntities_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered entity list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IntelligenceController_getBackendEntityArticles_v1: {
        parameters: {
            query?: {
                /** @description Filter by signal type */
                signal?: string;
            };
            header?: never;
            path: {
                /** @description Entity ID */
                entityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IntelligenceController_getBackendEntitySummary_v1: {
        parameters: {
            query?: {
                /** @description Filter by signal type */
                signal?: string;
            };
            header?: never;
            path: {
                /** @description Entity ID */
                entityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Entity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IntelligenceController_getBackendGlobalSignals_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Global signals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IntelligenceController_getAllSentimentCorrelations_v1: {
        parameters: {
            query?: {
                /** @description Number of days to shift events forward */
                lagDays?: number;
                /** @description Filter by signal type */
                signal?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of { entity, ticker, correlation, lagImpact } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CyberNewsController_getTickers_v1: {
        parameters: {
            query?: {
                /** @description Filter by topic */
                topic?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CyberNewsController_getRecent_v1: {
        parameters: {
            query?: {
                /** @description Max articles to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CyberNewsController_getTopics_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CyberNewsController_getSummary_v1: {
        parameters: {
            query?: {
                /** @description Filter by topic */
                topic?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CyberNewsController_getArticles_v1: {
        parameters: {
            query?: {
                /** @description Filter by topic */
                topic?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CyberNewsController_getCorrelations_v1: {
        parameters: {
            query?: {
                /** @description Lag days for correlation */
                lagDays?: number;
                /** @description Filter by topic */
                topic?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_getAudit_v1: {
        parameters: {
            query?: {
                /** @description Page size */
                limit?: number;
                /** @description Page offset */
                offset?: number;
                /** @description Filter by user ID */
                userId?: string;
                /** @description Filter by action name */
                action?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAuditDto"];
                };
            };
            /** @description Admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_triggerJob_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job name */
                job: "populate" | "news" | "trump" | "reddit" | "threatintel";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description { triggered: string, at: string } */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown job name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_stream_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream with typed event payloads for news, stocks, Trump posts, and threat intel updates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetricsController_getMetrics_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchController_streamResearch_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticker symbol */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream: { section, text?, sectionDone, done } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded (strict tier) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tavily API key not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchController_streamChat_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatBodyDto"];
            };
        };
        responses: {
            /** @description SSE stream: { text, done } then { done: true, messages } */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded (strict tier) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlpacaController_getBars_v1: {
        parameters: {
            query: {
                /** @description Trading date in YYYY-MM-DD format */
                date: string;
                /** @description Bar timeframe */
                timeframe?: "1Min" | "5Min" | "15Min" | "30Min" | "1Hour";
            };
            header?: never;
            path: {
                /** @description Ticker symbol (e.g. AAPL) */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        symbol?: string;
                        bars?: {
                            t?: string;
                            o?: number;
                            h?: number;
                            l?: number;
                            c?: number;
                            v?: number;
                            vw?: number;
                        }[];
                    };
                };
            };
            /** @description Missing or invalid date */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No data for this ticker/date */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StockController_getCompanies_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    StockController_correlationMatrix_v1: {
        parameters: {
            query?: {
                /** @description Number of days to shift column tickers forward */
                lagDays?: number;
                /** @description Rolling window size in days */
                windowDays?: number;
                /** @description Start of date range (YYYY-MM-DD) */
                startDate?: string;
                /** @description End of date range (YYYY-MM-DD) */
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description NxN Pearson correlation matrix keyed by company name */
                        matrix?: {
                            [key: string]: {
                                [key: string]: number | null;
                            };
                        };
                        tickers?: string[];
                        names?: string[];
                        lagDays?: number;
                        windowDays?: number;
                        startDate?: string | null;
                        endDate?: string | null;
                    };
                };
            };
            /** @description Invalid query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StockController_correlate_v1: {
        parameters: {
            query?: {
                /** @description Rolling window size in days */
                windowDays?: number;
                /** @description Number of days to shift events forward */
                lagDays?: number;
            };
            header?: never;
            path: {
                /** @description First ticker symbol (e.g. CRWD) */
                tickerA: string;
                /** @description Second ticker symbol (e.g. PANW) */
                tickerB: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationResultDto"];
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StockController_getSparklines_v1: {
        parameters: {
            query: {
                /** @description Comma-separated list of ticker symbols */
                tickers: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["SparklineDto"];
                    };
                };
            };
        };
    };
    StockController_getPresets_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticker symbol */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Map of strategy name → SimulationAction[] */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StockController_getTicker_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticker symbol (e.g. CRWD) */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        history?: {
                            quotes?: components["schemas"]["QuoteDto"][];
                        };
                        news?: Record<string, never>[];
                        /** @description Yahoo Finance summary data */
                        summary?: Record<string, never>;
                        analysis?: {
                            trend?: string;
                            momentum?: number;
                            volatility?: number;
                        };
                    };
                };
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StockController_simulate_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticker symbol */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateBodyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResultDto"];
                };
            };
            /** @description Invalid actions payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown ticker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
}
