import type { GraphNode, GraphEdge } from './types';

export const RAW_NODES: GraphNode[] = [
  {
    id: '/login',
    label: 'Login',
    route: '/login',
    category: 'auth',
    auth: 'public',
    description: 'Authenticates users with username/password or Google OAuth. Issues a JWT stored in localStorage.',
    apis: ['POST /auth/login', 'POST /auth/google'],
    features: [],
    dataFlows: [],
  },
  {
    id: '/register',
    label: 'Register',
    route: '/register',
    category: 'auth',
    auth: 'public',
    description: 'Creates a new user account with role "user".',
    apis: ['POST /auth/register'],
    features: [],
    dataFlows: [],
  },
  {
    id: '/',
    label: 'Home',
    route: '/',
    category: 'root',
    auth: 'protected',
    description: 'Multi-company overview with sparkline cards, a full Pearson correlation matrix across all tracked companies, and navigation to individual ticker pages.',
    apis: ['GET /', 'GET /sparklines', 'GET /correlation-matrix'],
    features: ['charts', 'correlations', 'tickers'],
    dataFlows: ['stock-price-sync', 'stock-to-stock-correlation'],
  },
  {
    id: '/:ticker',
    label: 'Ticker Analysis',
    route: '/:ticker',
    category: 'hub',
    auth: 'protected',
    description: 'Deep-dive page for a single ticker: OHLCV chart, pairwise correlations, news sentiment, Trump post correlation, threat intel correlation, AI research stream, chat, and trade simulation.',
    apis: [
      'GET /:ticker',
      'GET /correlate/:tickerA/:tickerB',
      'GET /correlate-trump/:ticker',
      'GET /correlate-trump/:ticker',
      'GET /trump-lag-impact/:ticker',
      'GET /threat-intel/correlate/:source/:ticker',
      'GET /news-analysis/:ticker',
      'POST /news-analyze/:ticker',
      'GET /news-correlation/:ticker',
      'GET /ollama/status',
      'GET /simulation-presets/:ticker',
      'POST /simulate/:ticker',
      'GET /research/:ticker',
      'POST /chat',
    ],
    features: ['charts', 'correlations', 'news', 'simulations', 'tickers'],
    dataFlows: [
      'stock-price-sync',
      'news-analysis-pipeline',
      'stock-to-stock-correlation',
      'trump-correlation',
      'threat-intel-correlation',
      'market-research-stream',
      'chat',
    ],
  },
  {
    id: '/threat-intel',
    label: 'Threat Intel',
    route: '/threat-intel',
    category: 'hub',
    auth: 'protected',
    description: 'Hub for cybersecurity threat intelligence feeds. Shows sync status for KEV, NVD, OTX, and MISP sources.',
    apis: ['GET /threat-intel/status'],
    features: ['threat-intel'],
    dataFlows: ['threat-intel-correlation'],
  },
  {
    id: '/threat-intel/list/kev',
    label: 'KEV List',
    route: '/threat-intel/list/kev',
    category: 'leaf',
    auth: 'protected',
    description: 'CISA Known Exploited Vulnerabilities catalog with search and ransomware filters.',
    apis: ['GET /threat-intel/list/kev'],
    features: ['threat-intel'],
    dataFlows: ['threat-intel-correlation'],
  },
  {
    id: '/threat-intel/list/nvd',
    label: 'NVD List',
    route: '/threat-intel/list/nvd',
    category: 'leaf',
    auth: 'protected',
    description: 'NIST National Vulnerability Database CVEs with severity filtering.',
    apis: ['GET /threat-intel/list/nvd'],
    features: ['threat-intel'],
    dataFlows: ['threat-intel-correlation'],
  },
  {
    id: '/threat-intel/list/otx',
    label: 'OTX List',
    route: '/threat-intel/list/otx',
    category: 'leaf',
    auth: 'protected',
    description: 'AlienVault OTX threat pulses related to tracked companies.',
    apis: ['GET /threat-intel/list/otx'],
    features: ['threat-intel'],
    dataFlows: ['threat-intel-correlation'],
  },
  {
    id: '/threat-intel/list/misp',
    label: 'MISP List',
    route: '/threat-intel/list/misp',
    category: 'leaf',
    auth: 'protected',
    description: 'MISP threat sharing platform events (requires MISP_URL configuration).',
    apis: ['GET /threat-intel/list/misp'],
    features: ['threat-intel'],
    dataFlows: ['threat-intel-correlation'],
  },
  {
    id: '/socials',
    label: 'Socials',
    route: '/socials',
    category: 'hub',
    auth: 'protected',
    description: 'Hub for social media monitoring — Trump Truth Social posts and Reddit discussions.',
    apis: [],
    features: ['social'],
    dataFlows: ['trump-correlation'],
  },
  {
    id: '/socials/truth-social',
    label: 'Truth Social',
    route: '/socials/truth-social',
    category: 'leaf',
    auth: 'protected',
    description: 'Trump Truth Social posts with per-ticker filtering and sentiment analysis.',
    apis: ['GET /trump-posts', 'GET /trump-posts/:ticker'],
    features: ['social'],
    dataFlows: ['trump-correlation'],
  },
  {
    id: '/socials/reddit',
    label: 'Reddit',
    route: '/socials/reddit',
    category: 'leaf',
    auth: 'protected',
    description: 'Reddit posts from tracked subreddits (r/cybersecurity, r/ExperiencedDevs).',
    apis: [],
    features: ['social'],
    dataFlows: [],
  },
  {
    id: '/intelligence',
    label: 'Intelligence',
    route: '/intelligence',
    category: 'hub',
    auth: 'protected',
    description: 'Entity-level news intelligence: NLP-extracted entities, sentiment signals, and urgency classification across all ingested articles.',
    apis: [],
    features: ['intelligence'],
    dataFlows: ['news-intelligence'],
  },
  {
    id: '/cyber-news',
    label: 'Cyber News',
    route: '/cyber-news',
    category: 'leaf',
    auth: 'protected',
    description: 'Cybersecurity news feed aggregated from RSS sources, with company and topic tagging.',
    apis: [],
    features: ['news'],
    dataFlows: ['news-analysis-pipeline'],
  },
  {
    id: '/events',
    label: 'Events',
    route: '/events',
    category: 'leaf',
    auth: 'protected',
    description: 'Market and security events timeline for tracking significant dates affecting tracked companies.',
    apis: [],
    features: ['charts'],
    dataFlows: ['stock-price-sync'],
  },
  {
    id: '/sec-archive',
    label: 'SEC Archive',
    route: '/sec-archive',
    category: 'leaf',
    auth: 'protected',
    description: 'Browse and sync SEC EDGAR filings (10-K, 10-Q, 8-K, DEF 14A, SC 13G/D) for tracked companies. Shows per-ticker coverage ranges.',
    apis: [
      'GET /api/v1/sec/tickers',
      'POST /api/v1/sec/sync',
      'GET /api/v1/sec/files/:ticker',
      'GET /api/v1/sec/coverage/:ticker',
    ],
    features: ['sec'],
    dataFlows: [],
  },
  {
    id: '/research',
    label: 'Research & Strategy',
    route: '/research',
    category: 'admin',
    auth: 'protected',
    description: 'Research hub with links to specialized analysis tools: insider trading intel, SEC EDGAR deep-dives, entity extraction, gov contracts, and USA spending data.',
    apis: [],
    features: [],
    dataFlows: ['market-research-stream'],
  },
  {
    id: '/research/insider-intel',
    label: 'Insider Intel',
    route: '/research/insider-intel',
    category: 'leaf',
    auth: 'protected',
    description: 'SEC Form 4 insider trading disclosures — track executive buy/sell activity for tracked tickers.',
    apis: [],
    features: [],
    dataFlows: [],
  },
  {
    id: '/research/edgar-uses',
    label: 'EDGAR Uses',
    route: '/research/edgar-uses',
    category: 'leaf',
    auth: 'protected',
    description: 'Reference page documenting EDGAR filing types and their research applications.',
    apis: [],
    features: [],
    dataFlows: [],
  },
  {
    id: '/research/edgar-deeper',
    label: 'EDGAR Deeper',
    route: '/research/edgar-deeper',
    category: 'leaf',
    auth: 'protected',
    description: 'Advanced EDGAR analysis: deeper filing exploration beyond the standard archive view.',
    apis: [],
    features: [],
    dataFlows: [],
  },
  {
    id: '/research/edgar-entities',
    label: 'EDGAR Entities',
    route: '/research/edgar-entities',
    category: 'leaf',
    auth: 'protected',
    description: 'Entity extraction from EDGAR filings — identify companies, people, and relationships mentioned in filings.',
    apis: [],
    features: [],
    dataFlows: [],
  },
  {
    id: '/research/gov-contracts',
    label: 'Gov Contracts',
    route: '/research/gov-contracts',
    category: 'leaf',
    auth: 'protected',
    description: 'Government contract awards data for tracked companies — track public sector revenue streams.',
    apis: [],
    features: [],
    dataFlows: [],
  },
  {
    id: '/research/usa-spending',
    label: 'USA Spending',
    route: '/research/usa-spending',
    category: 'leaf',
    auth: 'protected',
    description: 'USASpending.gov federal spending data for tracked companies.',
    apis: [],
    features: [],
    dataFlows: [],
  },
  {
    id: '/graph',
    label: 'App Map',
    route: '/graph',
    category: 'admin',
    auth: 'protected',
    description: 'Interactive node-link graph of all app pages, their API endpoints, features, and data flows.',
    apis: [],
    features: [],
    dataFlows: [],
  },
  {
    id: '/admin',
    label: 'Admin Dashboard',
    route: '/admin',
    category: 'admin',
    auth: 'admin',
    description: 'Admin overview: user management, system health, and navigation to audit log and feedback.',
    apis: [],
    features: [],
    dataFlows: [],
  },
  {
    id: '/admin/audit',
    label: 'Audit Log',
    route: '/admin/audit',
    category: 'admin',
    auth: 'admin',
    description: 'Paginated audit trail of user actions — filterable by userId and action type.',
    apis: ['GET /admin/audit'],
    features: [],
    dataFlows: [],
  },
  {
    id: '/admin/feedback',
    label: 'Feedback',
    route: '/admin/feedback',
    category: 'admin',
    auth: 'admin',
    description: 'UI feedback entries captured from the InspectDOM overlay — review and approve DOM-level feedback.',
    apis: [],
    features: [],
    dataFlows: [],
  },
];

export const RAW_EDGES: GraphEdge[] = [
  // Parent → child (structural hierarchy)
  { id: 'e-home-ticker',         source: '/',               target: '/:ticker',                      type: 'parent-child' },
  { id: 'e-ti-kev',             source: '/threat-intel',   target: '/threat-intel/list/kev',         type: 'parent-child' },
  { id: 'e-ti-nvd',             source: '/threat-intel',   target: '/threat-intel/list/nvd',         type: 'parent-child' },
  { id: 'e-ti-otx',             source: '/threat-intel',   target: '/threat-intel/list/otx',         type: 'parent-child' },
  { id: 'e-ti-misp',            source: '/threat-intel',   target: '/threat-intel/list/misp',        type: 'parent-child' },
  { id: 'e-soc-truth',          source: '/socials',        target: '/socials/truth-social',          type: 'parent-child' },
  { id: 'e-soc-reddit',         source: '/socials',        target: '/socials/reddit',                type: 'parent-child' },
  { id: 'e-res-insider',        source: '/research',       target: '/research/insider-intel',        type: 'parent-child' },
  { id: 'e-res-uses',           source: '/research',       target: '/research/edgar-uses',           type: 'parent-child' },
  { id: 'e-res-deeper',         source: '/research',       target: '/research/edgar-deeper',         type: 'parent-child' },
  { id: 'e-res-entities',       source: '/research',       target: '/research/edgar-entities',       type: 'parent-child' },
  { id: 'e-res-gov',            source: '/research',       target: '/research/gov-contracts',        type: 'parent-child' },
  { id: 'e-res-usa',            source: '/research',       target: '/research/usa-spending',         type: 'parent-child' },
  { id: 'e-admin-audit',        source: '/admin',          target: '/admin/audit',                   type: 'parent-child' },
  { id: 'e-admin-feedback',     source: '/admin',          target: '/admin/feedback',                type: 'parent-child' },
  { id: 'e-admin-research',     source: '/admin',          target: '/research',                      type: 'parent-child' },
  { id: 'e-admin-graph',        source: '/admin',          target: '/graph',                         type: 'parent-child' },

  // Data-flow cross-edges
  { id: 'df-ti-ticker',         source: '/threat-intel',   target: '/:ticker',                      type: 'data-flow' },
  { id: 'df-truth-ticker',      source: '/socials/truth-social', target: '/:ticker',               type: 'data-flow' },
  { id: 'df-ticker-cybernews',  source: '/:ticker',        target: '/cyber-news',                   type: 'data-flow' },
  { id: 'df-ticker-intel',      source: '/:ticker',        target: '/intelligence',                 type: 'data-flow' },
];
